version: '3'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      #- REDIS_PASSWORD=password # if you need setting password
      - ALLOW_EMPTY_PASSWORD=yes # if you need setting password, please comment out
    hostname: redis
    ports: # docker publish port 6379 to 6379 (將 docker 內部 ip 6379, 跟外部 6379 做連結)
      - "6379:6379"
    volumes:
      - 'redis:/bitnami/redis/data'
      # share volumes of docker container to outside volume, let data persist
      # 將 docker container 的 volumes 跟外部 volumes 做連結, 
      # 讓資料不會因為, container close or update, 而遺失
    restart: always
    networks:
        - dev
        
networks:
  dev:

volumes:
  redis: